const themeData = {
  light: {
    text: "#111827",
    textSecond: "#90959F",
    background: "#FFFFFF",
    backgroundSecond: "rgba(0,0,0,0.051)",
    tabIconDefault: "#9BBDF8",
    tabIconSelected: "#699CF4",
    primary: "#699CF4",
    danger: "#F86F6F",
    warning: "#FE8A1F",
    success: "#1BB937",
    input: "#F9FAFB",
    icon: "#9CA3AF",
    border: "#EEEFF2",
    contrastText: "white",
  },
  dark: {
    text: "#FFFFFF",
    textSecond: "#ffff",
    background: "#21232A",
    backgroundSecond: "#2D3039",
    tabIconDefault: "#9BBDF8",
    tabIconSelected: "#699CF4",
    primary: "#699CF4",
    danger: "#F86F6F",
    warning: "#FE8A1F",
    success: "#A7D2A5",
    input: "#2C313F",
    icon: "#9CA3AF",
    border: "#2C313F",
    contrastText: "white",
  },
};

export default themeData;
